sudo: required
language: c
compiler:
  - gcc
#  - clang

#Use this to prepare the system to install prerequisites or dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libglfw2 libglfw-dev libfreetype6 libfreetype6-dev libftgl2 libftgl-dev libglew1.6-dev libglew1.6

#Use this to install any prerequisites or dependencies necessary to run your buildlibglew1.6

#install: apt-get install libglfw3 libglfw3-dev libfreetype6 libfreetype6-dev libftgl2 libftgl-dev libglew-dev libglew

#Use this to prepare your build for testing
#e.g. copy database configurations, environment variables, etc.
#before_script:

# Change this to your needs
script: make clean && make
